### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by igor-toporet** [craiggwilson/mongo-dotnet-odata#1]
Hi Craig,

seems no single required package was included.

Cheers,
Igor

**Comment by craiggwilson** [comment]
They should get restored at build time if you have nuget package restore enabled.  If not, then you'll either need to turn it on or pull the packages manually.  

This project is not ready for use as of yet.  If you'd like to help, I'd love the help.

**Comment by igor-toporet** [comment]
Thanks for pointing on nuget package restore, didn't know about that.

Generally I'd like to help, but my spare time is sooooo limited, I'm mostly busy with kids. Anyhow let me know please what I can do for you.
